// Portfolio excerpt from Job Agent (src/connectors/company-site.ts — safety header and per-hop URL vetting). Shown for reading only; not runnable on its own.
// Imports point at modules not included in this repository.

/**
 * Company-direct fetching (ADR-025). The ONLY code in this project that fetches
 * an arbitrary company web page, and the only place the rules below are
 * enforced.
 *
 * THE SAFETY PROPERTY, STATED ONCE: this connector refuses any host but the one
 * on the `job_target_companies` row it was given. Not "prefers"; refuses. The
 * host comes from `careers_host`, which Postgres GENERATED from `careers_url` at
 * write time — so the check reads a stored value rather than re-deriving one
 * from a string a caller passed in, and a caller cannot widen it by parsing
 * differently.
 *
 * THE MODEL NEVER SUPPLIES A HOST. `fetch_company_page` and
 * `fetch_company_jobs` take a `company_id` and a PATH. The origin is looked up
 * from the database row. There is deliberately no tool anywhere in this project
 * that accepts a URL from the model and fetches it — that is the difference
 * between this connector and the `web_fetch` ADR-025 rejected.
 *
 * WHY NOT APIFY. Apify covers LinkedIn, and search_jobs already owns it. A
 * company's own careers page is the case Apify does not cover, which is the
 * entire reason `job_target_companies` exists as the LITERAL counterpart to
 * `job_search_directions`'s semantic intent.
 *
 * WHAT AN UNTRUSTED URL CAN STILL NOT REACH. Shalev types these URLs, and typed
 * input is untrusted input, so every one of these is enforced per request and
 * per redirect hop:
 *
 *   - scheme must be http or https (no file:, no gopher:, no data:)
 *   - host must equal the row's careers_host exactly, after lowercasing
 *   - literal IP hosts in private, loopback, link-local, CGNAT, multicast or
 *     reserved ranges are refused — this is what stops 169.254.169.254 and
 *     friends, which is the cloud-metadata endpoint every SSRF write-up starts
 *     with
 *   - names that resolve inside the network (localhost, *.local, *.internal,
 *     metadata.google.internal) are refused by name as well
 *   - when a DNS resolver is available, the RESOLVED addresses are checked too,
 *     so a public name pointing at 127.0.0.1 does not get through
 *   - redirects are followed manually, capped, and re-checked in full at every
 *     hop — an allowed host redirecting to an internal one is the classic
 *     bypass, and `redirect: "follow"` would take it silently
 *   - the response is capped in bytes and in wall-clock time, so a hostile or
 *     merely enormous page cannot exhaust the isolate
 *   - only HTML/plain-text content types are read at all
 *
 * PAGE TEXT IS DATA, NEVER INSTRUCTIONS. What comes back here reaches the model
 * as tool output. The system prompt already states that job descriptions are
 * data; the same holds, more so, for a whole page fetched from the open web.
 */

export type CompanySiteTarget = {
  companyId: string;
  companyName: string;
  /** The row's own careers URL — the origin every fetch is resolved against. */
  careersUrl: string;
  /** Generated by Postgres at write time. The allowlist, of exactly one host. */
  careersHost: string;
};

// … (types omitted)

const DEFAULT_MAX_BYTES = 400_000;
const DEFAULT_TIMEOUT_MS = 20_000;
const DEFAULT_MAX_REDIRECTS = 3;

/**
 * Hostnames refused by name, before DNS is even consulted.
 *
 * `metadata.google.internal` and `metadata.goog` are the GCP metadata service;
 * the AWS/Azure equivalent is an IP literal and is caught by the range check.
 */
const BLOCKED_HOSTNAMES = new Set([
  "localhost",
  "metadata",
  "metadata.google.internal",
  "metadata.goog",
  "instance-data",
]);

const BLOCKED_HOST_SUFFIXES = [".local", ".internal", ".localhost", ".home.arpa"];

/**
 * True for an address nothing on the public internet should be answering on.
 *
 * Covers IPv4 private/loopback/link-local/CGNAT/broadcast/multicast/reserved and
 * the IPv6 equivalents, including IPv4-mapped IPv6 (`::ffff:127.0.0.1`), which
 * is the form that slips past a naive IPv4-only check.
 */
export function isBlockedAddress(address: string): boolean {
  const value = address
    .trim()
    .toLowerCase()
    .replace(/^\[|\]$/g, "");

  // IPv4-mapped IPv6 — unwrap and judge as IPv4.
  const mapped = /^::ffff:(\d+\.\d+\.\d+\.\d+)$/.exec(value);
  if (mapped) return isBlockedAddress(mapped[1] as string);

  if (/^\d+\.\d+\.\d+\.\d+$/.test(value)) {
    const parts = value.split(".").map((p) => Number.parseInt(p, 10));
    if (parts.length !== 4 || parts.some((p) => !Number.isInteger(p) || p < 0 || p > 255)) {
      return true; // Malformed: refuse rather than guess.
    }
    const [a, b] = parts as [number, number, number, number];
    if (a === 0) return true; // "this network"
    if (a === 10) return true; // private
    if (a === 127) return true; // loopback
    if (a === 169 && b === 254) return true; // link-local, incl. 169.254.169.254
    if (a === 172 && b >= 16 && b <= 31) return true; // private
    if (a === 192 && b === 168) return true; // private
    if (a === 100 && b >= 64 && b <= 127) return true; // CGNAT
    if (a === 192 && b === 0) return true; // IETF protocol assignments
    if (a >= 224) return true; // multicast + reserved + broadcast
    return false;
  }

  if (value.includes(":")) {
    if (value === "::" || value === "::1") return true; // unspecified, loopback
    if (value.startsWith("fe80")) return true; // link-local
    if (/^f[cd]/.test(value)) return true; // unique local
    if (value.startsWith("ff")) return true; // multicast
    return false;
  }

  // Not an IP literal at all.
  return false;
}

function isBlockedHostname(hostname: string): boolean {
  const host = hostname.toLowerCase();
  if (BLOCKED_HOSTNAMES.has(host)) return true;
  if (BLOCKED_HOST_SUFFIXES.some((suffix) => host.endsWith(suffix))) return true;
  return isBlockedAddress(host);
}

/**
 * Every per-hop check in one place, so a redirect target is judged by exactly
 * the same rules as the original URL. Splitting these would be how a bypass
 * eventually appears.
 */
async function vetUrl(
  candidate: URL,
  allowedHost: string,
  resolveHost: ResolveHost | undefined,
): Promise<CompanySiteRefusal | null> {
  if (candidate.protocol !== "https:" && candidate.protocol !== "http:") {
    return {
      reason: "blocked_scheme",
      message: `Refused ${candidate.protocol}//… — only http and https are fetched.`,
    };
  }

  const host = candidate.hostname.toLowerCase();

  if (host !== allowedHost.toLowerCase()) {
    return {
      reason: "blocked_host",
      message: `Refused ${host} — this company is pinned to ${allowedHost}, and nothing else is fetched for it.`,
    };
  }

  if (isBlockedHostname(host)) {
    return {
      reason: "blocked_address",
      message: `Refused ${host} — it names a loopback, private or link-local address.`,
    };
  }

  if (resolveHost) {
    let addresses: string[];
    try {
      addresses = await resolveHost(host);
    } catch {
      return { reason: "network_error", message: `Could not resolve ${host}.` };
    }
    const blocked = addresses.find(isBlockedAddress);
    if (blocked) {
      return {
        reason: "blocked_address",
        message: `Refused ${host} — it resolves to ${blocked}, which is not a public address.`,
      };
    }
  }

  return null;
}

/**
 * Resolves what the model asked for against the company's own careers URL.
 *
 * A relative path is joined to the row's URL. An absolute URL is accepted only
 * so the model can pass back a link it read off the listing page verbatim — and
 * it still has to survive `vetUrl`, so an absolute URL pointing anywhere else is
 * refused exactly like any other foreign host.
 */
export function resolveTargetUrl(target: CompanySiteTarget, pathOrUrl?: string): URL | null {
  try {
    if (!pathOrUrl || pathOrUrl.trim() === "") return new URL(target.careersUrl);
    return new URL(pathOrUrl, target.careersUrl);
  } catch {
    return null;
  }
}

// … (fetch loop with manual redirects, byte/time caps, HTML-to-text and same-host link extraction omitted)
